name = "london-portfolio-backend"
main = "src/index.js"
compatibility_date = "2024-09-01"

[vars]
ALLOW_ORIGIN = "https://rightmove-london-portfolio.pages.dev,*.rightmove-london-portfolio.pages.dev,https://london-property-analysis.uk,*.london-property-analysis.uk"

[observability]
enabled = true

[observability.logs]
enabled = true