name = "london-portfolio-backend"
main = "src/index.js"
compatibility_date = "2024-09-01"

[vars]
ALLOW_ORIGIN = "https://rightmove-london-portfolio.pages.dev,*.rightmove-london-portfolio.pages.dev,https://london-property-analysis.uk,*.london-property-analysis.uk"
SNOWFLAKE_ACCOUNT = "KA89655.eu-west2.gcp.snowflakecomputing.com"
# Cortex Agent configuration
SNOWFLAKE_AGENT_DATABASE = "SNOWFLAKE_INTELLIGENCE"
SNOWFLAKE_AGENT_SCHEMA = "AGENTS"
SNOWFLAKE_AGENT_NAME = "RIGHTMOVE_ANALYSIS"
# Cortex Search configuration
SNOWFLAKE_SEARCH_DATABASE = "RIGHTMOVE_LONDON_SELL"
SNOWFLAKE_SEARCH_SCHEMA = "CLOUDRUN_DXLVF"
SNOWFLAKE_SEARCH_SERVICE = "UNSTRUCTURED_RAG"

[observability]
enabled = true

[observability.logs]
enabled = true