search_services: # List all Cortex Search services
  - service_name: "UNSTRUCTURED_RAG"
    description: > # Describe contents of the search service"
      "Search services that explore unstructured data"
    database_name: "RIGHTMOVE_LONDON_SELL"
    schema_name: "CLOUDRUN_DXLVF"
analyst_services: # List all Cortex Analyst semantic models/views
  - service_name: "STRUCTURED_QA" # Create descriptive name for the service
    semantic_model: "@RIGHTMOVE_LONDON_SELL.CLOUDRUN_DXLVF.RIGHTMOVE_SEMANTIC_STAGE/STRUCTURED_QA.yaml" # Fully-qualify semantic YAML model (stage path) or Semantic View
    description: > # Describe contents of the analyst service"
      "Semantic text-to-SQL over your cleaned Rightmove tables, returning governed metrics and slice-and-dice answers."

other_services: # Set desired tool groups to True to enable tools for that group
  object_manager: True # Perform basic operations against Snowflake's most common objects such as creation, dropping, updating, and more.
  query_manager: True # Run LLM-generated SQL managed by user-configured permissions.
  semantic_manager: True # Discover and query Snowflake Semantic Views and their components.
sql_statement_permissions: # List SQL statements to explicitly allow (True) or disallow (False).
  # - All: True # To allow everything, uncomment and set All: True.
  - Alter: True
  - Command: True
  - Comment: True
  - Commit: True
  - Create: True
  - Delete: True
  - Describe: True
  - Drop: True
  - Insert: True
  - Merge: True
  - Rollback: True
  - Select: True
  - Transaction: True
  - TruncateTable: True
  - Unknown: False # To allow unknown or unmapped statement types, set Unknown: True.
  - Update: True
  - Use: True
